const state = {
  experienceStore:
    [
      {
        id: 1,
        data_start: "14.01.2023",
        data_finish_en: "Present",
        data_finish_ua: "Дотепер",
        data_finish_es: "Actualidad",
        company_en: "Self-employed",
        company_ua: "Самозайнятий",
        company_es: "Autónomo",
        job_en: "3D Frontend Developer (React • Three.js • WebGPU)",
        job_ua: "3D Frontend-розробник (React • Three.js • WebGPU)",
        job_es: "Desarrollador frontend 3D (React • Three.js • WebGPU)",
        main_duties_en: "Designing, developing, and evolving interactive web applications and high-performance graphics systems using React, Three.js, WebGL, and WebGPU. Creating modern visual solutions, including 3D scenes, shaders, GPU computing, and interactive graphical interfaces. Designing scalable frontend architectures, optimizing rendering and performance, and preparing production-ready solutions.",
        main_duties_ua: "Проєктування, розробка та розвиток інтерактивних вебзастосунків і високопродуктивних графічних систем із використанням React, Three.js, WebGL і WebGPU. Створення сучасних візуальних рішень, включаючи 3D-сцени, шейдери, GPU-обчислення та інтерактивні графічні інтерфейси. Проєктування масштабованої frontend-архітектури, оптимізація продуктивності, рендерингу та підготовка рішень до production.",
        main_duties_es: "Diseño, desarrollo y evolución de aplicaciones web interactivas y sistemas gráficos de alto rendimiento utilizando React, Three.js, WebGL y WebGPU. Creación de soluciones visuales modernas, incluyendo escenas 3D, shaders, computación en GPU e interfaces gráficas interactivas. Diseño de arquitecturas frontend escalables, optimización del rendimiento y del renderizado, y preparación de soluciones listas para producción.",
        related_duties_en: "Defining the technical and visual direction of projects, conducting R&D in modern graphics technologies, and contributing to user experience (UX) design. Providing consulting on frontend architecture, WebGL, WebGPU, Three.js, and the integration of interactive 3D graphics into commercial products and presentation-oriented web applications.",
        related_duties_ua: "Формування технічної та візуальної концепції проєктів, проведення досліджень (R&D) сучасних графічних технологій і проєктування користувацького досвіду (UX). Консультування щодо архітектури frontend-рішень, використання WebGL, WebGPU, Three.js та впровадження інтерактивної 3D-графіки у продуктові й презентаційні вебзастосунки.",
        related_duties_es: "Definición de la visión técnica y visual de los proyectos, investigación y desarrollo (I+D) de tecnologías gráficas modernas y diseño de la experiencia de usuario (UX). Asesoramiento en arquitectura frontend, WebGL, WebGPU, Three.js e integración de gráficos 3D interactivos en aplicaciones web comerciales y de presentación.",
        tasks_en: "Developing interactive 3D scenes, visual systems, and graphical interfaces using React, Three.js, React Three Fiber, WebGL, and WebGPU. Creating Vertex and Fragment Shaders, exploring GPU computing (GPGPU), Raymarching, and modern rendering techniques. Implementing complex object interactions, animations, user workflows, and state management systems. Designing modular frontend architectures, integrating 3D content into SPA/PWA applications, optimizing rendering, GPU resource management, and application performance, as well as preparing solutions for production deployment and future scalability.",
        tasks_ua: "Розробка інтерактивних 3D-сцен, візуальних систем і графічних інтерфейсів із використанням React, Three.js, React Three Fiber, WebGL і WebGPU. Створення Vertex і Fragment Shader’ів, дослідження можливостей GPU-обчислень (GPGPU), Raymarching і сучасних технологій рендерингу. Реалізація складної логіки взаємодії об’єктів, анімацій, користувацьких сценаріїв і систем керування станом. Проєктування модульної архітектури frontend-застосунків, інтеграція 3D-контенту в SPA/PWA, оптимізація рендерингу, керування ресурсами та продуктивності GPU-застосунків. Підготовка проєктів до production і подальшого масштабування.",
        tasks_es: "Desarrollo de escenas 3D interactivas, sistemas visuales e interfaces gráficas utilizando React, Three.js, React Three Fiber, WebGL y WebGPU. Creación de Vertex y Fragment Shaders, investigación en computación sobre GPU (GPGPU), Raymarching y técnicas modernas de renderizado. Implementación de lógica compleja para la interacción de objetos, animaciones, flujos de usuario y gestión de estado. Diseño de arquitecturas frontend modulares, integración de contenido 3D en aplicaciones SPA/PWA, optimización del renderizado, la gestión de recursos de GPU y el rendimiento general de las aplicaciones, así como preparación de soluciones para producción y su futura escalabilidad.",
        skills: "React, Three.js, React Three Fiber (R3F), WebGL, WebGPU, TSL (Three.js Shading Language), JavaScript (ES6+), TypeScript, Shader Programming, Vertex Shaders, Fragment Shaders, GPU Computing (GPGPU), Raymarching, GPU Instancing, Graphics Pipeline, Frontend Architecture, Real-time Interactive Systems, 3D Graphics for Web, State Management, Performance Optimization, SPA / PWA, HTML5, CSS3 / SCSS, Git, UI/UX Collaboration, Technical Design, Cross-browser Compatibility."
      },
      {
        id: 2,
        data_start: "27.12.2016",
        data_finish_en: "13.01.2023",
        data_finish_ua: "13.01.2023",
        data_finish_es: "13.01.2023",
        company_en: "Yugov & D Ltd",
        company_ua: "ТОВ \"Югов & Д\"",
        company_es: "\"Yugov & D\" SRL",
        job_en: "Chief Executive Officer",
        job_ua: "Генеральний директор",
        job_es: "Director General (CEO)",
        main_duties_en: "Strategic and operational management of the company, including administrative leadership, activity planning, and control of key business processes. Making managerial and technical decisions at the intersection of business, technology, and production.",
        main_duties_ua: "Стратегічне та операційне управління компанією, включно з адміністративним керівництвом, плануванням діяльності та контролем ключових бізнес-процесів. Прийняття управлінських і технічних рішень на перетині бізнесу, технологій і виробництва.",
        main_duties_es: "Gestión estratégica y operativa de la empresa, incluyendo liderazgo administrativo, planificación de actividades y control de los procesos clave del negocio. Toma de decisiones directivas y técnicas en la intersección entre negocio, tecnología y producción.",
        related_duties_en: "Participation in the company’s digital transformation, including development of online presence, implementation of digital marketing tools, design of web interfaces, and involvement in frontend development. Collaboration with technical specialists and production engineers.",
        related_duties_ua: "Участь у цифровій трансформації компанії, розвиток онлайн-присутності, впровадження цифрових маркетингових інструментів, проєктування веб-інтерфейсів та участь у розробці фронтенд-рішень. Взаємодія з технічними спеціалістами та виробничими інженерами.",
        related_duties_es: "Participación en la transformación digital de la empresa, desarrollo de la presencia online, implementación de herramientas de marketing digital, diseño de interfaces web y participación en el desarrollo frontend. Colaboración con especialistas técnicos e ingenieros de producción.",
        tasks_en: "Developed the company’s corporate identity and logo. Designed and built the company website using Joomla CMS. Set up and managed advertising campaigns on Google, YouTube, Facebook, and Instagram. Created informational video materials and digital content for online channels. Integrated the website with Google Merchant Center and other Google services. Registered and maintained the company’s presence on Google Maps. In collaboration with manufacturing engineers, contributed to the development and programming of a custom coffee roasting machine. Participated in the development of coffee recipes and blends. Set up and maintained IT infrastructure, including workstations, local network, and basic server solutions.",
        tasks_ua: "Розробив фірмовий стиль і логотип компанії. Спроєктував і створив корпоративний веб-сайт із використанням CMS Joomla. Налаштував та керував рекламними кампаніями в Google, YouTube, Facebook і Instagram. Створював інформаційні відеоматеріали та цифровий контент для онлайн-каналів. Інтегрував сайт із Google Merchant Center та сервісами Google. Зареєстрував і супроводжував присутність компанії в Google Maps. У співпраці з інженерами заводу-виробника брав участь у розробці та програмуванні ексклюзивного ростера для обсмаження кави. Долучався до розробки рецептур і кавових купажів. Забезпечував налаштування та підтримку ІТ-інфраструктури, включно з робочими станціями, локальною мережею та базовими серверними рішеннями.",
        tasks_es: "Desarrollé la identidad corporativa y el logotipo de la empresa. Diseñé y construí el sitio web corporativo utilizando CMS Joomla. Configuré y gestioné campañas publicitarias en Google, YouTube, Facebook e Instagram. Creé materiales de vídeo informativos y contenido digital para canales online. Integré el sitio web con Google Merchant Center y otros servicios de Google. Registré y gestioné la presencia de la empresa en Google Maps. En colaboración con ingenieros del fabricante, participé en el desarrollo y programación de un tostador de café exclusivo. Contribuí al desarrollo de recetas y mezclas de café. Configuré y mantuve la infraestructura de TI, incluyendo estaciones de trabajo, red local y soluciones básicas de servidores.",
        skills: "Project Management, Business Strategy, Digital Marketing, Frontend Development, HTML, CSS3, JavaScript, PHP, Git, CMS Joomla, Google Analytics, Google Ads, UI/UX Design, Adobe Photoshop, Adobe Illustrator, Adobe Premiere, IT Infrastructure, Negotiation, Technical Communication."
      },
      {
        id: 3,
        data_start: "15.01.2001",
        data_finish_en: "13.01.2023",
        data_finish_ua: "13.01.2023",
        data_finish_es: "13.01.2023",
        company_en: "LIS Ltd",
        company_ua: "ТОВ \"ЛИС\"",
        company_es: "\"LIS\" SRL",
        job_en: "Chief Executive Officer",
        job_ua: "Генеральний директор",
        job_es: "Director General (CEO)",
        main_duties_en: "Full company management, including strategic planning, organization of operational activities, and development of new business areas. Oversight of financial, technical, and commercial processes.",
        main_duties_ua: "Повне управління компанією, включно зі стратегічним плануванням, організацією операційної діяльності та розвитком нових напрямів бізнесу. Контроль фінансових, технічних і комерційних процесів.",
        main_duties_es: "Gestión integral de la empresa, incluyendo la planificación estratégica, la organización de las actividades operativas y el desarrollo de nuevas áreas de negocio. Supervisión de los procesos financieros, técnicos y comerciales.",
        related_duties_en: "Development of the company’s digital channels, web design, and participation in client-side interface development. Supervision of technical solutions related to automated systems and programmable equipment.",
        related_duties_ua: "Розвиток цифрових каналів компанії, веб-дизайн та участь у розробці клієнтських інтерфейсів. Нагляд за технічними рішеннями, пов’язаних з автоматизованими системами та програмованим обладнанням.",
        related_duties_es: "Desarrollo de los canales digitales de la empresa, diseño web y participación en el desarrollo de interfaces del lado del cliente. Supervisión de soluciones técnicas relacionadas con sistemas automatizados y equipos programables.",
        tasks_en: "Developed the company’s logo and visual identity. Designed and built the corporate website based on WordPress. Localized vending machine software by translating interfaces from German. Programmed vending machines, coin acceptors, and bill acceptors. Set up and managed advertising campaigns on Google and YouTube. Registered and maintained the company’s presence on Google Maps. Developed an accounting and monitoring system for vending machines. Configured workstations and maintained the company’s local network.",
        tasks_ua: "Розробка логотипа та візуальної ідентичності компанії. Проєктування та створення корпоративного веб-сайту на базі WordPress. Локалізація програмного забезпечення торгових автоматів шляхом перекладу інтерфейсів з німецької мови. Програмування торгових автоматів, монетоприймачів і банкнотоприймачів. Налаштування та управління рекламними кампаніями в Google і YouTube. Реєстрація та супровід присутності компанії в Google Maps. Розробка системи бухгалтерського обліку та моніторингу торгових автоматів. Налаштування робочих станцій і підтримка локальної мережі компанії.",
        tasks_es: "Desarrollo del logotipo y de la identidad visual de la empresa. Diseño y creación del sitio web corporativo basado en WordPress. Localización del software de máquinas expendedoras mediante la traducción de interfaces desde el alemán. Programación de máquinas expendedoras, aceptadores de monedas y aceptadores de billetes. Configuración y gestión de campañas publicitarias en Google y YouTube. Registro y mantenimiento de la presencia de la empresa en Google Maps. Desarrollo de un sistema de contabilidad y monitoreo de máquinas expendedoras. Configuración de estaciones de trabajo y mantenimiento de la red local de la empresa.",
        skills: "Business Management, Project Management, Embedded Systems Basics, Automation Systems, Frontend Development, HTML, CSS3, JavaScript, PHP, WordPress, Google Analytics, Google Ads, Digital Marketing, UI/UX Design, Technical Documentation, IT Operations, Negotiation."
      },
      {
        id: 4,
        data_start: "12.09.2000",
        data_finish_en: "30.06.2004",
        data_finish_ua: "30.06.2004",
        data_finish_es: "30.06.2004",
        company_en: "PAWOL Ltd",
        company_ua: "ТОВ \"Павол\"",
        company_es: "\"PAWOL\" SRL",
        job_en: "Deputy Chief Executive Officer",
        job_ua: "Заступник генерального директора",
        job_es: "Subdirector General",
        main_duties_en: "Development of the company’s foreign economic activities and identification of new innovative business directions. Analysis of markets, partners, and opportunities for international cooperation.",
        main_duties_ua: "Розвиток зовнішньоекономічної діяльності компанії та пошук нових інноваційних напрямів бізнесу. Аналіз ринків, партнерів і перспектив міжнародної співпраці.",
        main_duties_es: "Desarrollo de la actividad de comercio exterior de la empresa y búsqueda de nuevos enfoques innovadores de negocio. Análisis de mercados, socios y oportunidades de cooperación internacional.",
        related_duties_en: "Marketing, analytics, and establishment of the company’s basic web presence. Participation in the design of digital materials and presentation solutions.",
        related_duties_ua: "Маркетинг, аналітика та формування базової веб-присутності компанії. Участь у проєктуванні цифрових матеріалів і презентаційних рішень.",
        related_duties_es: "Marketing, analítica y establecimiento de la presencia web básica de la empresa. Participación en el diseño de materiales digitales y soluciones de presentación.",
        tasks_en: "Developed the company’s logo and basic corporate identity. Created a simple landing page to present services and business areas. Configured computer equipment and the local network. Conducted negotiations and concluded foreign trade contracts with partners from Germany, Italy, the Czech Republic, Spain, Turkey, and China. Represented the company at international exhibitions, conferences, and in interactions with government authorities.",
        tasks_ua: "Розробка логотипа та базового фірмового стилю компанії. Створення простого лендингу для презентації послуг і напрямів діяльності. Налаштування комп’ютерної техніки та локальної мережі. Ведення переговорів і укладання зовнішньоекономічних контрактів (Німеччина, Італія, Чехія, Іспанія, Туреччина, Китай). Представлення інтересів компанії на міжнародних виставках, конференціях та у взаємодії з державними органами.",
        tasks_es: "Desarrollo del logotipo y de la identidad corporativa básica de la empresa. Creación de una landing page sencilla para la presentación de servicios y áreas de actividad. Configuración de equipos informáticos y de la red local. Negociación y formalización de contratos de comercio exterior (Alemania, Italia, República Checa, España, Turquía, China). Representación de los intereses de la empresa en ferias internacionales, conferencias y en la interacción con organismos gubernamentales.",
        skills: "International Business, Contract Negotiation, Business Development, Marketing Strategy, Digital Marketing, Web Design Basics, HTML, CMS WordPress, Business Analytics, Strategic Thinking, Presentation Skills, Management."
      },
    ]
};
const getters = {};
const mutations = {};
const actions = {};
export default {
  state,
  getters,
  mutations,
  actions
};